export const ACTION_TYPES = {
  SET_CHAT_IMAGE: "SET_CHAT_IMAGE",
  SET_CHAT_MESSAGES: "SET_CHAT_MESSAGES",
  SET_CHAT_NAME: "SET_CHAT_NAME",
  SET_NEW_CHAT_MESSAGE: "SET_NEW_CHAT_MESSAGE",
  SET_USER_LOGIN: "SET_USER_LOGIN",
};
